

spring:
  # 邮件相关配置
  mail:
    # stmp 地址
    host: smtp.qq.com
    # 端口号，默认都是 465
    port: 465
    username: 209026725@qq.com
    password: hidkdgphjakrcajh
    # 使用协议
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enabled: true
  # 开发阶段需要关闭 thymeleaf 的缓存
  thymeleaf:
    cache: false
  # 数据库相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    # 数据库连接池相关配置
    hikari:
      # 最大连接数
      maximum-pool-size: 20
      # 最小连接数
      minimum-pool-size: 5
      # 超时等待时间
      idle-timeout: 30000
  # 设置文件上传属性
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # redis相关配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  # kafka相关配置
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      # 是否自动提交
      enable-auto-commit: true
      # 自动提交的频率
      auto-commit-interval: 3000
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9200
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200
  # Quartz相关配置
  quartz:
    # 将任务保存到数据库中
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: auto
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5

# elasticsearch 的地址
elasticsearch.host: 127.0.0.1
# elasticsearch 的端口号
elasticsearch.port: 9200

logging:
  level:
    edu.hue.community.dao: debug

community:
  path:
    # 上传文件存放位置
    upload: F:/项目/牛客社区/data/upload
    # 域名
    domain: http://localhost:8080