

spring:
  # 邮件相关配置
  mail:
    # stmp 地址
    host: smtp.qq.com
    # 端口号，默认都是 465
    port: 465
    username: 209026725@qq.com
    password: hidkdgphjakrcajh
    # 使用协议
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enabled: true
  # 开发阶段需要关闭 thymeleaf 的缓存
  thymeleaf:
    cache: false
  # 数据库相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    # 数据库连接池相关配置
    hikari:
      # 最大连接数
      maximum-pool-size: 20
      # 最小连接数
      minimum-pool-size: 5
      # 超时等待时间
      idle-timeout: 30000
  # 设置文件上传属性
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# mybatis \u76F8\u5173\u914D\u7F6E
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    # \u5F00\u542F\u9A7C\u5CF0\u547D\u540D\u6CD5
#    map-underscore-to-camel-case: true
#    # \u4F7F\u7528\u81EA\u52A8\u751F\u6210\u4E3B\u952E
#    use-generated-keys: true

logging:
  level:
    edu.hue.community.dao: debug

community:
  path:
    # 上传文件存放位置
    upload: F:/项目/牛客社区/data/upload
    # 域名
    domain: http://localhost:8080